In [1]:
%env CUDA_VISIBLE_DEVICES='-1'
import tensorflow as tf
import numpy as np
import pandas as pd
import glob
import os
import loader
from IPython.display import display, Audio

env: CUDA_VISIBLE_DEVICES='-1'


In [2]:
tokens = []
fps = []
root_dir = 'data/Gamemaster_Audio_16KHz'
for fp in glob.iglob(os.path.join(root_dir, '**/*.wav'), recursive=True):
    fps.append(fp)
    tokens.append(os.path.basename(fp).split('.')[0].split(' ')[0].split('_')[0])

In [24]:
vocab = set(tokens + ['<UNK>'])
vocab = pd.Series(range(len(vocab)), index=vocab, dtype=np.int32)
print(vocab)

bear            0
hyena           1
clock           2
potions         3
printer         4
fun             5
river           6
cat             7
tape            8
water           9
pick           10
sweeping       11
stones         12
pencil         13
car            14
rock           15
voice          16
squeaky        17
bubble         18
mine           19
witch          20
switch         21
goblin         22
snowball       23
hydraulic      24
cooking        25
twinkle        26
scissors       27
fart           28
weapon         29
             ... 
beep          151
item          152
music         153
turkey        154
explosion     155
toy           156
boiling       157
swamp         158
retro         159
lever         160
pigeon        161
goat          162
hum           163
fireball      164
coin          165
bone          166
pig           167
casting       168
bird          169
cinematic     170
fear          171
background    172
strange       173
ice           174
kick      

In [25]:
word_ids = vocab.loc[tokens].values
print(word_ids)
len(word_ids)

[120 120 120 ... 153 153 153]


8076

In [27]:
vocab.to_csv('vocab_test.csv', header=False)
vocab_from_file = pd.read_csv('vocab_test.csv', header=None, index_col=0, squeeze=True).astype(np.int32)
print(vocab_from_file)
print(vocab_from_file.loc['<UNK>'])
print(vocab_from_file.index[117])

0
bear            0
hyena           1
clock           2
potions         3
printer         4
fun             5
river           6
cat             7
tape            8
water           9
pick           10
sweeping       11
stones         12
pencil         13
car            14
rock           15
voice          16
squeaky        17
bubble         18
mine           19
witch          20
switch         21
goblin         22
snowball       23
hydraulic      24
cooking        25
twinkle        26
scissors       27
fart           28
weapon         29
             ... 
beep          151
item          152
music         153
turkey        154
explosion     155
toy           156
boiling       157
swamp         158
retro         159
lever         160
pigeon        161
goat          162
hum           163
fireball      164
coin          165
bone          166
pig           167
casting       168
bird          169
cinematic     170
fear          171
background    172
strange       173
ice           174
kick    

In [6]:
print(vocab.index[179])
print(vocab.loc['<UNK>'])

toliet
145


In [30]:
list(vocab.index)

['bear',
 'hyena',
 'clock',
 'potions',
 'printer',
 'fun',
 'river',
 'cat',
 'tape',
 'water',
 'pick',
 'sweeping',
 'stones',
 'pencil',
 'car',
 'rock',
 'voice',
 'squeaky',
 'bubble',
 'mine',
 'witch',
 'switch',
 'goblin',
 'snowball',
 'hydraulic',
 'cooking',
 'twinkle',
 'scissors',
 'fart',
 'weapon',
 'cash',
 'ducks',
 'crickets',
 'special',
 'wolf',
 'crow',
 'potion',
 'cave',
 'monkey',
 'phone',
 'chime',
 'fire',
 'taser',
 'seal',
 'duck',
 'shimmer',
 'troll',
 'cork',
 'fan',
 'fuse',
 'gorilla',
 'birds',
 'hyro',
 'light',
 'spray',
 'chicken',
 'elevator',
 'happy',
 'zombie',
 'chair',
 'truck',
 'hacking',
 'healing',
 'points',
 'metallic',
 'cartoon',
 'elec',
 'magic',
 'spell',
 'nature',
 'bell',
 'tas',
 'knife',
 'underwater',
 'typing',
 'horse',
 'sword',
 'collect',
 'small',
 'boat',
 'ghost',
 'frog',
 'owl',
 'whistle',
 'comedy',
 'bowling',
 'manhole',
 'gun',
 'tyre',
 'vanish',
 'grasshopper',
 'rooster',
 'gear',
 'zebra',
 'door',
 'dist

In [64]:
index = np.random.randint(len(vocab))
word = vocab.index[index]
index = vocab[index]
print(index)
print(word)

151
beep


In [59]:
tf.enable_eager_execution()

In [8]:
x = [[2.]]
m = tf.matmul(x, x)
print("hello, {}".format(m))

hello, [[4.]]


In [9]:
fps_dataset = tf.data.Dataset.from_tensor_slices(fps)
word_ids_dataset = tf.data.Dataset.from_tensor_slices(word_ids)
dataset = tf.data.Dataset.zip((fps_dataset, word_ids_dataset))
dataset = dataset.shuffle(buffer_size=len(fps))
dataset = dataset.batch(64, drop_remainder=True)
iterator = dataset.make_one_shot_iterator()

Instructions for updating:
Colocations handled automatically by placer.


In [10]:
iterator.get_next()

(<tf.Tensor: id=23, shape=(64,), dtype=string, numpy=
 array([b'data/Gamemaster_Audio_16KHz\\Magic_Spells\\light_in_dark_spell_05.wav',
        b'data/Gamemaster_Audio_16KHz\\Animal_Impersonations\\snake_2_hiss_01.wav',
        b'data/Gamemaster_Audio_16KHz\\Guns_Weapons\\Bow_Arrow\\bow_crossbow_arrow_shoot_type1_07.wav',
        b'data/Gamemaster_Audio_16KHz\\Comedy_Cartoon\\beep_zap_fun_03.wav',
        b'data/Gamemaster_Audio_16KHz\\Retro\\retro_jump_collect_bonus_02.wav',
        b'data/Gamemaster_Audio_16KHz\\Miscellaneous\\Typing\\typing_keystroke_single_soft_05.wav',
        b'data/Gamemaster_Audio_16KHz\\Magic_Spells\\magic_general_item_collect_02.wav',
        b'data/Gamemaster_Audio_16KHz\\Retro_Classic\\Weapons\\retro_laser_gun_shoot_23.wav',
        b'data/Gamemaster_Audio_16KHz\\Zombie\\zombie_voice_groan_croak_06.wav',
        b'data/Gamemaster_Audio_16KHz\\Magic_Spells\\magic_spell_book_page_flips_12.wav',
        b'data/Gamemaster_Audio_16KHz\\Animal_Impersonations\\chi

In [11]:
vocab.index[122]

'beach'

In [12]:
x, y, vocab = loader.decode_extract_and_batch(
        fps,
        batch_size=64,
        slice_len=16384,
        decode_fs=16000,
        decode_num_channels=2,
        decode_fast_wav=True,
        slice_first_only=True,
        prefetch_gpu_num=-1,
        extract_labels=True,
        shuffle=True,
        repeat=True,
        shuffle_buffer_size=1,
        vocab_dir='train_gamemaster')

Loaded vocab file: train_gamemaster\vocab.csv
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, use
    tf.py_function, which takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.
    

For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.



In [13]:
print(y)
print(vocab)

tf.Tensor(
[156 103 136  45 121 112 161 142 117  61 121 159 121 145 117 133 135  63
 117 136  79  98  99 121  82  44  18 150  24 121   8  86 117 117 156 136
  27  98 121 121  32  98 117   1 121   8 121 121 121 155 123  98  32 140
 162 144  15  70  82  25 156 149 117  63], shape=(64,), dtype=int64)
0
lighter          0
pigeon           1
<UNK>            2
stones           3
magic            4
coin             5
turkey           6
vanish           7
zombie           8
steam            9
whoosh          10
sweeping        11
hum             12
hyro            13
unsheathe       14
sheep           15
toliet          16
pig             17
cow             18
pencil          19
lizard          20
rain            21
fun             22
fantasy         23
tas             24
bird            25
goat            26
glass           27
dog             28
toy             29
              ... 
casting        151
grasshopper    152
shaker         153
river          154
bell           155
music          

In [14]:
vocab.index[79]

'explosion'

In [15]:
idx = np.random.randint(64)
audio = tf.squeeze(x)[idx].numpy().T
label_id = y[idx].numpy()
display(Audio(audio, rate=16000))
print(vocab.index[label_id])

zombie


In [16]:
embedding_size = 100
embeddings = tf.Variable(tf.random_normal(shape=(len(vocab), embedding_size)), trainable=True)

In [17]:
tf.nn.embedding_lookup(embeddings, vocab['monkey'])

<tf.Tensor: id=166, shape=(100,), dtype=float32, numpy=
array([ 0.5977211 , -0.28028223, -0.9938906 ,  1.5989482 , -0.17579788,
        0.34570223,  1.4036567 ,  0.5487447 , -0.5669077 , -0.4226916 ,
        0.60701764, -0.80137235,  0.47495502,  0.0561896 ,  0.21504436,
       -0.51723444,  0.1066265 ,  1.343644  , -0.2916247 ,  0.38603112,
        0.08152105, -2.3123782 , -0.1998377 , -0.22560324,  0.60357195,
       -1.321113  , -0.56467116, -0.35141766,  1.1826735 ,  0.4350596 ,
        1.3927317 , -1.3605627 , -0.90730876, -0.64513654, -0.4986903 ,
       -0.04123936,  1.0049641 , -0.7667808 ,  0.07609525, -0.48973513,
        1.7575154 ,  0.2840021 , -0.06053606, -1.030775  ,  1.4885257 ,
        1.1901042 , -0.60230875, -1.1392053 , -0.42002353,  1.0252796 ,
       -1.9293994 , -0.7133971 , -0.19297075,  0.2802753 ,  3.7554605 ,
       -0.8147698 ,  1.4228759 ,  0.9237147 , -0.5334813 ,  0.31761095,
        0.429219  ,  1.6956215 ,  0.51307046,  0.10887808, -0.6693384 ,
       -